import { useState, type FormEvent } from 'react'
import { ArrowRight, Cloud, Laptop, LoaderCircle, Mail, ShieldCheck } from 'lucide-react'
import { cloud, firebaseConfigured } from '../lib/firebase'
import { useStore } from '../lib/store'
import { Brand, Modal } from './ui'

export function AccountModal({ onClose }: { onClose: () => void }) {
  const { data, updateProfile, notify } = useStore()
  const [name, setName] = useState(data.profile.name)
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [signUp, setSignUp] = useState(true)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const authenticate = async (google = false) => {
    setBusy(true); setError('')
    try { if (google) await cloud.google(); else await cloud.email(email, password, signUp ? name.trim() : undefined); notify('Welcome! Your progress can now sync across devices.'); onClose() }
    catch (e) { const message = e instanceof Error ? e.message : 'Sign-in failed.'; setError(message.includes('invalid-credential') ? 'That email and password don’t match. Please try again.' : message.includes('email-already-in-use') ? 'An account already exists with that email. Try signing in instead.' : message.includes('popup-closed') ? 'The sign-in window was closed. You can try again.' : message.includes('unauthorized-domain') ? 'This deployment needs to be added to Firebase’s authorized domains. You can continue on this device.' : 'Could not sign in. Check your details and connection, then try again.') }
    finally { setBusy(false) }
  }
  const submit = (e: FormEvent) => { e.preventDefault(); if (!firebaseConfigured) { updateProfile({ name: name.trim() || 'Alex' }); onClose() } else void authenticate() }
  return <Modal title="Your learner profile" onClose={onClose} className="account-modal"><Brand /><div className="modal-heading"><span className="eyebrow">A SPACE THAT’S YOURS</span><h2>{firebaseConfigured ? signUp ? 'Your next chapter awaits.' : 'Good to see you again.' : 'Make yourself at home.'}</h2><p>{firebaseConfigured ? 'Keep your discoveries and progress with you, wherever you learn.' : 'Every great learning journey starts with you. What should we call you?'}</p></div>{firebaseConfigured && <><button className="button secondary full" disabled={busy} onClick={() => authenticate(true)}><svg width="17" height="17" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.8 12.2c0-.7-.1-1.4-.2-2.1H12v4h5.5a4.7 4.7 0 0 1-2 3.1v2.6h3.3c1.9-1.8 3-4.4 3-7.6Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.4l-3.3-2.6c-.9.6-2 1-3.4 1-2.6 0-4.8-1.8-5.6-4.1H3v2.7A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.4 13.9A6 6 0 0 1 6.1 12c0-.7.1-1.3.3-1.9V7.4H3A10 10 0 0 0 2 12c0 1.6.4 3.2 1 4.6l3.4-2.7Z"/><path fill="#EA4335" d="M12 6c1.5 0 2.8.5 3.9 1.5l2.9-2.9A9.5 9.5 0 0 0 12 2a10 10 0 0 0-9 5.4l3.4 2.7A6 6 0 0 1 12 6Z"/></svg>Continue with Google</button><div className="form-divider"><span>or continue with email</span></div></>}<form onSubmit={submit}>{(!firebaseConfigured || signUp) && <label className="field-label">Your name<input autoComplete="given-name" required maxLength={40} value={name} onChange={e => setName(e.target.value)} placeholder="What should we call you?" /></label>}{firebaseConfigured && <><label className="field-label">Email address<input type="email" autoComplete="email" value={email} required onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label className="field-label">Password<input type="password" autoComplete={signUp ? 'new-password' : 'current-password'} value={password} minLength={8} required onChange={e => setPassword(e.target.value)} placeholder="At least 8 characters" /></label></>}{error && <div className="error-note" role="alert">{error}</div>}<button className="button primary full" disabled={busy || ((!firebaseConfigured || signUp) && !name.trim())}>{busy ? <LoaderCircle size={17} className="spin" /> : firebaseConfigured ? <Mail size={16} /> : <Laptop size={16} />}{firebaseConfigured ? signUp ? 'Create my account' : 'Sign in' : 'Save my learner profile'}<ArrowRight size={16} /></button></form>{firebaseConfigured ? <button className="text-button account-toggle" onClick={() => { setSignUp(!signUp); setError('') }}>{signUp ? 'Already have an account? Sign in' : 'New here? Create an account'}</button> : <div className="device-note"><ShieldCheck size={19} /><p><strong>Your progress stays on this device.</strong>No account needed. You can export a backup anytime from Settings. Cloud sign-in is not enabled in this preview.</p></div>}<div className="account-footnote">{firebaseConfigured ? <Cloud size={13} /> : <ShieldCheck size={13} />}Your learning. Your pace. Always.</div></Modal>
}
