import { ArrowRight, BookOpen, CheckCircle2, ChevronDown, Compass, ShieldCheck, Sparkles, Target } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Modal } from './ui'
const faqs = [
  ['How does the diagnostic work?', 'You’ll answer five multiple-choice questions, one per core skill in your chosen topic. There’s no timer and no grade. Your answers help us decide which modules need more attention and which can be quick refreshers.'],
  ['How is my path personalized?', 'Your path keeps concepts in a sensible learning order. Skills you missed receive focused lessons and more time; skills you already know become shorter refreshers. If an AI provider is connected, questions and lesson content can also be generated for you. Otherwise, complete curated lessons are adapted to your results.'],
  ['What completes a module?', 'Read the lesson, explore any resources you find useful, then answer the two practice questions. Getting at least one correct completes the module. You can retry as often as you like, and we keep your best score.'],
  ['Where is my progress saved?', 'By default, your profile, paths, practice scores, and saved resources stay in this browser’s local storage. They persist when you return on the same browser. Clearing browser data removes them, so export a backup in Settings. When Firebase is configured and you sign in, progress syncs to your private cloud account.'],
  ['How do I delete or move my data?', 'In Settings, export a JSON backup or import a previous backup. Reset learning data permanently removes progress from this device and, when signed in, your cloud learning record. This does not delete your Firebase authentication account.'],
]
export function HelpModal({ onClose }: { onClose: () => void }) {
  return <Modal title="A little guidance for your journey" onClose={onClose} className="help-modal"><span className="modal-hero-icon"><Compass size={26} /></span><div className="modal-heading"><span className="eyebrow">YOU DON’T HAVE TO FIGURE IT OUT ALONE</span><h2>A little guidance goes a long way.</h2><p>Here’s how to make LearnPath your own.</p></div><div className="help-steps">{[[Target, 'Find your starting point', 'Choose a topic and answer 5 quick questions.'], [Sparkles, 'Meet your learning path', 'Get a clear route built around what you need.'], [CheckCircle2, 'Make progress that lasts', 'Learn, practice, and celebrate the small wins.']].map(([Icon, title, description]) => { const I = Icon as typeof Target; return <div key={String(title)}><I size={20} /><span><strong>{String(title)}</strong><p>{String(description)}</p></span></div> })}</div><div className="faq-list">{faqs.map(([title, body]) => <details key={title}><summary>{title}<ChevronDown size={16} /></summary><p>{body}</p></details>)}</div><div className="privacy-callout"><ShieldCheck size={18} /><p>No public profiles. No leaderboards. Just your learning journey. External resources and videos open with their provider’s own privacy policies.</p></div><Link to="/topics" className="button primary full" onClick={onClose}><BookOpen size={16} />Let’s find something to learn<ArrowRight size={16} /></Link></Modal>
}
